2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_setup.py:_flush():80] Configure stats pid to 990747
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_setup.py:_flush():80] Loading settings from /home/chris/.config/wandb/settings
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_setup.py:_flush():80] Loading settings from /home/chris/Documents/OpenLimb/wandb/settings
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/chris/Documents/OpenLimb/wandb/run-20250721_152708-e36o201a/logs/debug.log
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/chris/Documents/OpenLimb/wandb/run-20250721_152708-e36o201a/logs/debug-internal.log
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x727c00d4f3b0>
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_init.py:init():830] calling init triggers
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'lr': 0.001, 'eta_min': 1e-05, 'batch_size': 256, 'log': True, 'seed': 42, '_wandb': {}}
2025-07-21 15:27:08,155 INFO    MainThread:990747 [wandb_init.py:init():871] starting backend
2025-07-21 15:27:08,374 INFO    MainThread:990747 [wandb_init.py:init():874] sending inform_init request
2025-07-21 15:27:08,385 INFO    MainThread:990747 [wandb_init.py:init():882] backend started and connected
2025-07-21 15:27:08,386 INFO    MainThread:990747 [wandb_run.py:_label_probe_notebook():1304] probe notebook
2025-07-21 15:27:08,386 INFO    MainThread:990747 [wandb_init.py:init():953] updated telemetry
2025-07-21 15:27:08,388 INFO    MainThread:990747 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-21 15:27:09,414 INFO    MainThread:990747 [wandb_init.py:init():1029] starting run threads in backend
2025-07-21 15:27:09,469 INFO    MainThread:990747 [wandb_run.py:_console_start():2458] atexit reg
2025-07-21 15:27:09,469 INFO    MainThread:990747 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-21 15:27:09,469 INFO    MainThread:990747 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-21 15:27:09,469 INFO    MainThread:990747 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-21 15:27:09,471 INFO    MainThread:990747 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-21 15:27:09,471 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:27:09,475 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:27:09,475 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:27:09,476 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:27:09,481 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:27:09,482 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:27:09,498 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:27:09,502 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:27:09,503 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:27:09,526 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:27:09,530 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:27:09,530 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:27:09,540 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:27:09,543 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:27:09,543 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:27:14,690 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:27:14,694 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:27:14,694 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:30:37,541 WARNING MsgRouterThr:990747 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 231, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 216, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-21 15:30:37,542 INFO    MsgRouterThr:990747 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-21 15:30:37,830 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:31:07,656 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:31:07,656 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:31:07,674 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:31:07,702 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:31:07,703 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:31:07,731 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-07-21 15:31:07,755 INFO    MainThread:990747 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-07-21 15:31:07,756 INFO    MainThread:990747 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-07-21 15:31:07,775 INFO    MainThread:990747 [wandb_run.py:_finish():2224] finishing run cvail-imperial-college-london/PointNet++ - FaceScanData/e36o201a
2025-07-21 15:31:07,775 ERROR   MainThread:990747 [wandb_init.py:init():1616] [no run ID] error in wandb.init()
Traceback (most recent call last):
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1606, in init
    return wi.init(run_settings, run_config, run_printer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    self._wl.finish_all_active_runs()
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 161, in finish_all_active_runs
    run.finish()
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 443, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2212, in finish
    return self._finish(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2225, in _finish
    with telemetry.context(run=self) as tel:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 764, in _telemetry_callback
    self._telemetry_flush()
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 777, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/chris/Documents/OpenLimb/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 15:31:07,959 INFO    MainThread:990747 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
